services:
  stock-exchange-api:
    container_name: stock-exchange-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "1212:1212"
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1212"
      - STORAGE_TYPE=memory
    command: /bin/bash -c "java -jar /app.jar"